# Generated by Django 5.2.8 on 2025-12-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ví dụ: zh, ja, ko, fr...', max_length=10, unique=True, verbose_name='Mã ngôn ngữ')),
                ('name', models.CharField(max_length=100, verbose_name='Tên hiển thị')),
                ('flag_icon', models.CharField(default='globe', help_text='Tên icon trong hệ thống Wagtail (VD: globe, site, user...)', max_length=50, verbose_name='Icon (Wagtail)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('is_core', models.BooleanField(default=False, editable=False, verbose_name='Là ngôn ngữ gốc')),
            ],
            options={
                'verbose_name': 'Cấu hình Ngôn ngữ',
                'verbose_name_plural': 'Cấu hình Ngôn ngữ',
            },
        ),
        migrations.AddField(
            model_name='systemlabel',
            name='extra_translations',
            field=models.JSONField(blank=True, default=dict, help_text='Dữ liệu dịch cho các ngôn ngữ bổ sung (JSON format).', verbose_name='Ngôn ngữ khác'),
        ),
        migrations.AlterField(
            model_name='systemlabel',
            name='app',
            field=models.CharField(choices=[('common', 'Dùng chung (Common)'), ('equipment', 'Thiết bị (Equipment)'), ('details', 'Thông số (Details)'), ('auth', 'Tài khoản (Auth)'), ('report', 'Báo cáo (Report)'), ('core', 'Hệ thống (Core)')], default='common', max_length=50, verbose_name='Phân hệ'),
        ),
        migrations.AlterField(
            model_name='systemlabel',
            name='key',
            field=models.SlugField(max_length=100, verbose_name='Mã định danh (Key)'),
        ),
    ]
