# Generated by Django 5.2.8 on 2025-12-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemlanguage_systemlabel_extra_translations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemlanguage',
            options={'ordering': ['-is_core', 'code'], 'verbose_name': 'Cấu hình Ngôn ngữ', 'verbose_name_plural': 'Cấu hình Ngôn ngữ'},
        ),
        migrations.RemoveField(
            model_name='systemlanguage',
            name='flag_icon',
        ),
        migrations.AddField(
            model_name='systemlanguage',
            name='flag',
            field=models.CharField(default='🏳️', help_text='Copy và paste emoji cờ vào đây (VD: 🇻🇳, 🇺🇸, 🇨🇳).', max_length=10, verbose_name='Quốc kỳ (Emoji)'),
        ),
        migrations.AlterField(
            model_name='systemlabel',
            name='extra_translations',
            field=models.JSONField(blank=True, default=dict, help_text='Dữ liệu JSON cho các ngôn ngữ bổ sung.', verbose_name='Ngôn ngữ khác'),
        ),
        migrations.AlterField(
            model_name='systemlanguage',
            name='code',
            field=models.CharField(help_text='Ví dụ: vi, en, zh...', max_length=10, unique=True, verbose_name='Mã ngôn ngữ'),
        ),
    ]
