# Generated by Django 5.2.8 on 2025-12-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_systemlanguage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Prompt')),
                ('prompt_type', models.CharField(choices=[('translate_to_en', 'Dịch sang Tiếng Anh (Chuẩn hóa)'), ('translate_from_en', 'Dịch từ Tiếng Anh sang ngôn ngữ khác'), ('generate_desc', 'Tạo mô tả thiết bị')], max_length=50, verbose_name='Loại tác vụ')),
                ('scope', models.CharField(choices=[('system', 'Toàn hệ thống (System)'), ('app', 'Theo Phân hệ (App)'), ('specific', 'Cụ thể (Specific)')], default='system', max_length=20, verbose_name='Phạm vi')),
                ('target_app', models.CharField(blank=True, help_text='Nhập tên app (VD: equipment, details). Để trống nếu là System.', max_length=50, verbose_name='Áp dụng cho App')),
                ('content', models.TextField(help_text='Sử dụng các biến {text}, {source_lang}, {target_lang} để thay thế động.', verbose_name='Nội dung Prompt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sử dụng')),
            ],
            options={
                'verbose_name': 'Cấu hình AI Prompt',
                'verbose_name_plural': 'Cấu hình AI Prompt',
            },
        ),
        migrations.AlterField(
            model_name='systemlabel',
            name='extra_translations',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ngôn ngữ khác'),
        ),
        migrations.AlterField(
            model_name='systemlabel',
            name='text_vi',
            field=models.TextField(blank=True, default='', verbose_name='Tiếng Việt'),
        ),
        migrations.AlterField(
            model_name='systemlanguage',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Mã ngôn ngữ'),
        ),
        migrations.AlterField(
            model_name='systemlanguage',
            name='flag',
            field=models.CharField(default='🏳️', max_length=10, verbose_name='Quốc kỳ (Emoji)'),
        ),
    ]
