# Generated by Django 5.2.8 on 2025-12-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aiprompt_alter_systemlabel_extra_translations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemlabel',
            options={'verbose_name': 'Nhãn giao diện'},
        ),
        migrations.AlterField(
            model_name='aiprompt',
            name='content',
            field=models.TextField(verbose_name='Nội dung Prompt'),
        ),
        migrations.AlterField(
            model_name='aiprompt',
            name='prompt_type',
            field=models.CharField(choices=[('translate_to_en', 'Dịch sang Tiếng Anh (Chuẩn hóa)'), ('translate_from_en', 'Dịch từ Tiếng Anh sang ngôn ngữ khác'), ('pinyin_converter', 'Chuyển đổi Pinyin (Tiếng Trung)')], max_length=50, verbose_name='Loại tác vụ'),
        ),
        migrations.AlterField(
            model_name='aiprompt',
            name='scope',
            field=models.CharField(choices=[('system', 'Toàn hệ thống'), ('app', 'Theo Phân hệ'), ('specific', 'Cụ thể')], default='system', max_length=20, verbose_name='Phạm vi'),
        ),
        migrations.AlterField(
            model_name='aiprompt',
            name='target_app',
            field=models.CharField(blank=True, max_length=50, verbose_name='Áp dụng cho App'),
        ),
    ]
