# Generated by Django 5.2.8 on 2025-12-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_systemlabel_options_alter_aiprompt_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemlabel',
            name='extra_translations',
        ),
        migrations.AddField(
            model_name='systemlabel',
            name='text_fil',
            field=models.TextField(blank=True, verbose_name='Tiếng Filipino'),
        ),
        migrations.AddField(
            model_name='systemlabel',
            name='text_id',
            field=models.TextField(blank=True, verbose_name='Tiếng Indonesia'),
        ),
        migrations.AddField(
            model_name='systemlabel',
            name='text_km',
            field=models.TextField(blank=True, verbose_name='Tiếng Khmer'),
        ),
        migrations.AddField(
            model_name='systemlabel',
            name='text_lo',
            field=models.TextField(blank=True, verbose_name='Tiếng Lào'),
        ),
        migrations.AddField(
            model_name='systemlabel',
            name='text_ms',
            field=models.TextField(blank=True, verbose_name='Tiếng Malay'),
        ),
        migrations.AddField(
            model_name='systemlabel',
            name='text_my',
            field=models.TextField(blank=True, verbose_name='Tiếng Myanmar'),
        ),
        migrations.AddField(
            model_name='systemlabel',
            name='text_th',
            field=models.TextField(blank=True, verbose_name='Tiếng Thái'),
        ),
        migrations.AddField(
            model_name='systemlabel',
            name='text_zh',
            field=models.TextField(blank=True, verbose_name='Tiếng Trung (Giản thể)'),
        ),
        migrations.AddField(
            model_name='systemlabel',
            name='text_zh_pinyin',
            field=models.TextField(blank=True, help_text='Phiên âm Latin cho tiếng Trung', verbose_name='Pinyin (Trung)'),
        ),
    ]
