# Generated by Django 5.2.8 on 2025-12-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_systemlabel_extra_translations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompt',
            name='prompt_type',
            field=models.CharField(choices=[('translate_to_en', 'Dịch sang Tiếng Anh (Chuẩn hóa)'), ('translate_from_en', 'Dịch từ Tiếng Anh sang ngôn ngữ khác'), ('pinyin_converter', 'Chuyển đổi Pinyin (Tiếng Trung)'), ('generate_desc', 'Tự động tạo mô tả (Từ tên)')], max_length=50, verbose_name='Loại tác vụ'),
        ),
    ]
