# Generated by Django 5.2.8 on 2025-12-10 13:08

import django.db.models.deletion
import wagtail.fields
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên thiết bị')),
                ('kks_code', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Mã KKS')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Hãng sản xuất')),
                ('model_number', models.CharField(blank=True, max_length=255, verbose_name='Model / Type')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Mô tả / Nguyên lý')),
                ('audio_vi', models.FileField(blank=True, null=True, upload_to='tts/equip/vi/', verbose_name='Audio (VI)')),
                ('audio_en', models.FileField(blank=True, null=True, upload_to='tts/equip/en/', verbose_name='Audio (EN)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hình ảnh')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='area.functionallocation', verbose_name='Khu vực lắp đặt')),
                ('maintenance_manual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Tài liệu Bảo trì')),
                ('operation_manual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Tài liệu Vận hành')),
            ],
            options={
                'verbose_name': 'Thiết bị Vật lý',
                'verbose_name_plural': 'Thiết bị Vật lý',
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EquipmentDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC Address')),
                ('protocol', models.CharField(blank=True, choices=[('modbus', 'Modbus TCP/IP'), ('opcua', 'OPC UA'), ('mqtt', 'MQTT'), ('snmp', 'SNMP')], max_length=50, verbose_name='Giao thức')),
                ('dashboard_url', models.URLField(blank=True, verbose_name='Link Dashboard')),
                ('last_connected', models.DateTimeField(blank=True, null=True, verbose_name='Kết nối cuối')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online')),
                ('firmware_version', models.CharField(blank=True, max_length=50, verbose_name='Firmware')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_profile', to='equipment.equipment', verbose_name='Thiết bị vật lý')),
            ],
            options={
                'verbose_name': 'Thiết bị Số (Digital)',
                'verbose_name_plural': 'Thiết bị Số (Digital)',
            },
        ),
    ]
