# Generated by Django 5.2.8 on 2025-12-19 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_alter_detail_group'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='parameter_template',
            field=models.ForeignKey(blank=True, help_text='Chọn nhóm để tự động tạo danh sách thông số ban đầu. Có thể sửa đổi sau.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='details.detailgroup', verbose_name='Mẫu thông số (Template)'),
        ),
    ]
