# Generated by Django 5.2.8 on 2025-12-19 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_parameter_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='parameter_template',
        ),
    ]
