# Generated by Django 5.2.8 on 2025-12-10 13:08

import django.db.models.deletion
import wagtail.fields
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255, verbose_name='Tên khu vực/Hệ thống')),
                ('kks_code', models.CharField(blank=True, db_index=True, help_text='Mã định danh hệ thống (VD: 10LAC10).', max_length=50, null=True, verbose_name='Mã KKS')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Mô tả chức năng')),
                ('audio_vi', models.FileField(blank=True, null=True, upload_to='tts/area/vi/', verbose_name='Audio (VI)')),
                ('audio_en', models.FileField(blank=True, null=True, upload_to='tts/area/en/', verbose_name='Audio (EN)')),
                ('audio_cn', models.FileField(blank=True, null=True, upload_to='tts/area/cn/', verbose_name='Audio (CN)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Cập nhật cuối')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hình ảnh đại diện')),
                ('schematic_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Sơ đồ P&ID / Bản vẽ (PDF)')),
            ],
            options={
                'verbose_name': 'Khu vực & Hệ thống',
                'verbose_name_plural': 'Khu vực & Hệ thống',
            },
            bases=(models.Model, wagtail.models.preview.PreviewableMixin),
        ),
    ]
