# Generated by Django 5.2.8 on 2025-12-10 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionallocation',
            name='parent_selection',
            field=models.ForeignKey(blank=True, help_text='Để trống nếu đây là Khu vực gốc (Root).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_ref', to='area.functionallocation', verbose_name='Trực thuộc (Khu vực cha)'),
        ),
    ]
