# Generated by Django 5.2.8 on 2025-12-19 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_functionallocation_parent_selection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionallocation',
            options={'verbose_name': 'Khu vực', 'verbose_name_plural': 'Khu vực'},
        ),
    ]
