"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "core",

    # App mặc định được tạo ra khi chạy lệnh wagtail start
    "home",
    # App mặc định chứa view xử lý giao diện tìm kiếm ở Frontend
    "search",

    "area",
    "equipment",
    "details",

    # Cho phép tạo các biểu mẫu (Contact Form, Survey) ngay trong Admin mà không cần code cứng (hard-code)
    "wagtail.contrib.forms",
    # Quản lý chuyển hướng URL (301, 302)
    "wagtail.contrib.redirects",

    # Hỗ trợ nhúng nội dung từ bên thứ 3 (YouTube, Vimeo, Twitter)
    "wagtail.embeds",
    # Quản lý đa trang web (Multi-site)
    "wagtail.sites",
    # Quản lý người dùng và nhóm quyền (Groups) trong môi trường Wagtail
    "wagtail.users",
    # Dùng để tạo các phần nội dung tái sử dụng được (không phải là Page)
    "wagtail.snippets",
    # Quản lý các tệp tin không phải ảnh
    "wagtail.documents",
    # Quản lý thư viện ảnh
    "wagtail.images",
    # Cung cấp backend cho việc tìm kiếm nội dung (Indexing)
    "wagtail.search",
    # Giao diện quản trị (CMS Dashboard)
    "wagtail.admin",
    # Chứa các logic nền tảng
    "wagtail",

    # Giúp Wagtail xử lý quan hệ dữ liệu
    "modelcluster",
    # Hỗ trợ tính năng gắn thẻ (Tagging) cho bài viết và hình ảnh.
    "taggit",

    # Thư viện bên thứ 3 (không phải mặc định của Wagtail). Dùng để tạo bộ lọc dữ liệu (FilterSet) dễ dàng
    "django_filters",

    # Trang admin thuần của Django
    "django.contrib.admin",
    # Xác thực người dùng
    "django.contrib.auth",
    # Quản lý các loại model (cần thiết cho permissions)
    "django.contrib.contenttypes",
    # Lưu phiên đăng nhập
    "django.contrib.sessions",
    # Hiển thị thông báo
    "django.contrib.messages",
    # Quản lý file CSS/JS tĩnh
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            PROJECT_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        'OPTIONS': {
            # Tăng thời gian chờ lên 20 hoặc 30 giây (Mặc định là 5s)
            # Giúp script có thời gian đợi runserver nhả resource ra.
            'timeout': 20, 
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    PROJECT_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default storage settings
# See https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# Wagtail settings

WAGTAIL_SITE_NAME = "mysite"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}


# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "http://example.com"

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']


WAGTAILIMAGES_EXTENSIONS = ["gif", "jpg", "jpeg", "png", "webp", "svg"]

GEMINI_API_KEY = "AIzaSyBZSMN1sTK9MLXeIzxJ4S_3uCQQAN9mc6U"