# Generated by Django 5.2.8 on 2025-12-10 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhóm thông số')),
                ('description', models.TextField(blank=True, help_text='Mô tả các thông số thuộc nhóm này.', verbose_name='Mô tả nhóm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
            ],
            options={
                'verbose_name': 'Nhóm Thông số',
                'verbose_name_plural': 'Nhóm Thông số',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thông số')),
                ('unit', models.CharField(blank=True, help_text='VD: V, bar, m3/h', max_length=20, verbose_name='Đơn vị')),
                ('data_type', models.CharField(choices=[('num', 'Số (Number)'), ('text', 'Chữ (Text)'), ('bool', 'Đúng/Sai (Boolean)')], default='num', max_length=10, verbose_name='Kiểu dữ liệu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='details.detailgroup', verbose_name='Nhóm thông số')),
            ],
            options={
                'verbose_name': 'Thông số',
                'verbose_name_plural': 'Thông số',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('value', models.CharField(max_length=255, verbose_name='Giá trị')),
                ('measured_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đo')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='details.detail', verbose_name='Thông số')),
            ],
            options={
                'verbose_name': 'Giá trị',
                'verbose_name_plural': 'Giá trị',
                'ordering': ['sort_order'],
            },
        ),
    ]
