# Generated by Django 5.2.8 on 2025-12-19 02:02

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='group',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='details.detailgroup', verbose_name='Nhóm thông số'),
        ),
    ]
