# Generated by Django 5.2.8 on 2025-12-19 02:39

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_alter_detail_group'),
        ('equipment', '0003_remove_equipment_parameter_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='group',
        ),
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name': 'Danh mục Thông số', 'verbose_name_plural': 'Danh mục Thông số'},
        ),
        migrations.AlterModelOptions(
            name='equipmentvalue',
            options={'verbose_name': 'Thông số'},
        ),
        migrations.RemoveField(
            model_name='detail',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='unit',
        ),
        migrations.AlterUniqueTogether(
            name='equipmentvalue',
            unique_together={('equipment', 'detail')},
        ),
        migrations.AddField(
            model_name='detail',
            name='default_unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Đơn vị mặc định'),
        ),
        migrations.AddField(
            model_name='equipmentvalue',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Đơn vị (nếu khác)'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên thông số'),
        ),
        migrations.AlterField(
            model_name='equipmentvalue',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='details.detail', verbose_name='Tên thông số'),
        ),
        migrations.AlterField(
            model_name='equipmentvalue',
            name='equipment',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='equipment.equipment'),
        ),
        migrations.DeleteModel(
            name='DetailGroup',
        ),
        migrations.RemoveField(
            model_name='equipmentvalue',
            name='measured_at',
        ),
    ]
