# Generated by Django 5.2.8 on 2025-12-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_remove_detail_group_alter_detail_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('common', 'Dùng chung (Common)'), ('equipment', 'Thiết bị (Equipment)'), ('details', 'Thông số (Details)'), ('auth', 'Tài khoản (Auth)'), ('report', 'Báo cáo (Report)')], default='common', help_text='Nhãn này thuộc về chức năng nào?', max_length=50, verbose_name='Phân hệ')),
                ('key', models.SlugField(help_text='Mã dùng trong code (VD: btn_save, title_dashboard). Không được trùng trong cùng 1 App.', max_length=100, verbose_name='Mã định danh (Key)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả ngữ cảnh')),
                ('text_vi', models.TextField(default='', verbose_name='Tiếng Việt')),
                ('text_en', models.TextField(blank=True, verbose_name='Tiếng Anh')),
            ],
            options={
                'verbose_name': 'Nhãn giao diện',
                'verbose_name_plural': 'Nhãn giao diện',
                'unique_together': {('app', 'key')},
            },
        ),
    ]
