# Generated by Django 5.2.8 on 2025-12-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_systemlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlabel',
            name='app',
            field=models.CharField(choices=[('common', 'Dùng chung (Common)'), ('equipment', 'Thiết bị (Equipment)'), ('details', 'Thông số (Details)'), ('auth', 'Tài khoản (Auth)'), ('report', 'Báo cáo (Report)')], default='common', max_length=50, verbose_name='Phân hệ'),
        ),
        migrations.AlterField(
            model_name='systemlabel',
            name='key',
            field=models.SlugField(help_text='Mã dùng trong code (VD: btn_save, title_dashboard).', max_length=100, verbose_name='Mã định danh (Key)'),
        ),
    ]
