# Generated by Django 5.2.8 on 2025-12-19 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_alter_systemlabel_app_alter_systemlabel_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemLabel',
        ),
    ]
