# Generated by Django 5.2.8 on 2025-12-19 05:12

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_delete_systemlabel'),
        ('equipment', '0003_remove_equipment_parameter_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentvalue',
            options={'verbose_name': 'Thông số kỹ thuật', 'verbose_name_plural': 'Thông số kỹ thuật'},
        ),
        migrations.AlterField(
            model_name='detail',
            name='default_unit',
            field=models.CharField(blank=True, help_text='Ví dụ: bar, °C, A (Có thể để trống)', max_length=50, null=True, verbose_name='Đơn vị mặc định'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(help_text='Ví dụ: Áp suất, Nhiệt độ, Dòng điện...', max_length=255, verbose_name='Tên thông số'),
        ),
        migrations.AlterField(
            model_name='equipmentvalue',
            name='equipment',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='equipment.equipment', verbose_name='Thiết bị'),
        ),
    ]
