# Generated by Django 5.2.8 on 2025-12-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_alter_equipmentvalue_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='name',
        ),
        migrations.AddField(
            model_name='detail',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tên thông số (Tiếng Anh)'),
        ),
        migrations.AddField(
            model_name='detail',
            name='name_fil',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tiếng Filipino'),
        ),
        migrations.AddField(
            model_name='detail',
            name='name_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tiếng Indo'),
        ),
        migrations.AddField(
            model_name='detail',
            name='name_km',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tiếng Khmer'),
        ),
        migrations.AddField(
            model_name='detail',
            name='name_lo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tiếng Lào'),
        ),
        migrations.AddField(
            model_name='detail',
            name='name_ms',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tiếng Malay'),
        ),
        migrations.AddField(
            model_name='detail',
            name='name_my',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tiếng Myanmar'),
        ),
        migrations.AddField(
            model_name='detail',
            name='name_th',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tiếng Thái'),
        ),
        migrations.AddField(
            model_name='detail',
            name='name_vi',
            field=models.CharField(default='', max_length=255, verbose_name='Tên thông số (Tiếng Việt)'),
        ),
        migrations.AddField(
            model_name='detail',
            name='name_zh',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tên thông số (Tiếng Trung)'),
        ),
        migrations.AddField(
            model_name='detail',
            name='name_zh_pinyin',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pinyin'),
        ),
    ]
