# Generated by Django 5.2.8 on 2025-12-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_remove_detail_name_detail_name_en_detail_name_fil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Mô tả (Tiếng Anh)'),
        ),
        migrations.AddField(
            model_name='detail',
            name='description_fil',
            field=models.TextField(blank=True, verbose_name='Mô tả (Filipino)'),
        ),
        migrations.AddField(
            model_name='detail',
            name='description_id',
            field=models.TextField(blank=True, verbose_name='Mô tả (Indo)'),
        ),
        migrations.AddField(
            model_name='detail',
            name='description_km',
            field=models.TextField(blank=True, verbose_name='Mô tả (Khmer)'),
        ),
        migrations.AddField(
            model_name='detail',
            name='description_lo',
            field=models.TextField(blank=True, verbose_name='Mô tả (Lào)'),
        ),
        migrations.AddField(
            model_name='detail',
            name='description_ms',
            field=models.TextField(blank=True, verbose_name='Mô tả (Malay)'),
        ),
        migrations.AddField(
            model_name='detail',
            name='description_my',
            field=models.TextField(blank=True, verbose_name='Mô tả (Myanmar)'),
        ),
        migrations.AddField(
            model_name='detail',
            name='description_th',
            field=models.TextField(blank=True, verbose_name='Mô tả (Thái)'),
        ),
        migrations.AddField(
            model_name='detail',
            name='description_vi',
            field=models.TextField(blank=True, help_text='Để trống cả Việt và Anh để AI tự động sinh.', verbose_name='Mô tả (Tiếng Việt)'),
        ),
        migrations.AddField(
            model_name='detail',
            name='description_zh',
            field=models.TextField(blank=True, verbose_name='Mô tả (Tiếng Trung)'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='default_unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Đơn vị mặc định'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='name_vi',
            field=models.CharField(blank=True, default='', help_text='Nhập tên tiếng Việt (Bắt buộc nếu không có tiếng Trung).', max_length=255, verbose_name='Tên thông số (Tiếng Việt)'),
        ),
    ]
